# backend: gpu
data_path: data/CIFAR10
data_type: float
backend_type: CPU
# train or inference
model_type: train 
eval: true
epoches: 30
#for image is channel, width, height per image
data_shape: [3, 32, 32]
label_size: 10
batch_size: 128

fillers:
-
    type: Uniform
    name: f1
    high: 0.1
    low: -0.1

scheduler:
-
    type: GradientDescent
    name: op1
    learning_rate: 0.01
    step: 10
    change: 0.1
    momentum_coef: 0.9
    decay: 0.0

layers:
-
    type: Affine
    name: Affine1
    nout: 200
    filler: f1
    activation: 
        type: Rectlin
    optimizer: op1
-
    type: Affine
    name: Affine2
    nout: 10
    filler: f1
    activation: 
        type: Logistic
        short_cut: true
    optimizer: op1
-
    cost: 
        type: CrossEntropyBinary

callbacks:
-
    type: Progressbar
    step: 300

