# backend: gpu
data_path: data/MNIST
data_type: float
backend_type: GPU
# train or inference
model_type: train 
eval: true
epoches: 2
# for image is channel, width, height per image
data_shape: [1, 28, 28]
label_size: 10
batch_size: 128

fillers:
-
    type: Gaussian
    name: f1
    loc: 0.0
    scale: 0.1

layers:
-
    type: Conv
    name: Conv1
    stride: 1
    padding: 0
    fshape: [16, 1, 5, 5]
    filler: f1
    activation: 
        type: Rectlin
    optimizer: op1
    kernel: asm
-
    type: Pooling
    name: Pooling1
    fshape: 2
    stride: 2
    op: max
-
    type: Conv
    name: Conv2
    stride: 1
    padding: 0
    fshape: [32, 16, 5, 5]
    filler: f1
    activation:
        type: Rectlin
    optimizer: op1
    kernel: asm
-
    type: Pooling
    name: Pooling2
    fshape: 2
    stride: 2
    op: max
-
    type: Affine
    name: Affine1
    nout: 500
    filler: f1
    activation:
        type: Rectlin
    optimizer: op1
    kernel: asm
-
    type: Affine
    name: Affine2
    nout: 10
    filler: f1
    activation: 
        type: Logistic
        short_cut: true
    optimizer: op1
    kernel: asm
-
    cost: 
        type: CrossEntropyBinary

scheduler:
-
    type: GradientDescent
    name: op1
    learning_rate: 0.1
    step: 10
    change: 0.1
    momentum_coef: 0.9
    decay: 0.0

callbacks:
-
    type: Progressbar
    step: 100
