language: c++
compiler:
  - g++
cache:
  directories:
  - ${HOME}/glog
sudo: false
os:
  - linux
addons:
  apt:
    packages:
    - libboost-all-dev
    - libopenblas-dev
before_script:
  - export LD_LIBRARY_PATH=/usr/local/opt/openblas/library:$LD_LIBRARY_PATH
  - export LIBRARY_PATH=/usr/local/opt/openblas/libray:$LIBRARY_PATH
  - export CPLUS_INCLUDE_PATH=/opt/OpenBLAS/include:$CPLUS_INCLUDE_PATH
  - cd third-party/glog
  - ./configure --enable-shared --prefix=${HOME}/glog
  - touch configure.ac aclocal.m4 configure Makefile.am Makefile.in
  - make install -j4
  - cd ../..
  - export LD_LIBRARY_PATH=${HOME}/glog/lib:$LD_LIBRARY_PATH
  - export LIBRARY_PATH=${HOME}/glog/lib:$LIBRARY_PATH
  - export CPLUS_INCLUDE_PATH=${HOME}/glog/include:$CPLUS_INCLUDE_PATH
  - export OMP_NUM_THREADS=16
  - make -j4
script:
  - ./scripts/tests/cpu.sh
