language: c++
compiler:
  - g++
sudo: true
os:
  - linux
before_install:
  - sudo apt-get -y update
  - sudo apt-get install -y libboost-system-dev
  - sudo apt-get install -y libboost-date-time-dev
  - sudo apt-get install -y libboost-chrono-dev
  - sudo apt-get install -y libboost-thread-dev
  - sudo apt-get install -y libgoogle-glog-dev
  - sudo apt-get install -y libopenblas-dev
before_script:
  - export OMP_NUM_THREADS=16
  - make -j4
script:
  - ./scripts/tests/cpu.sh
