language: c++
compiler:
  - g++
cache:
  directories:
  - ${HOME}/openblas
  - ${HOME}/glog
sudo: false
os:
  - linux
addons:
  apt:
    packages:
    - libboost-all-dev
before_script:
  - cd third-party/openblas
  - make USE_OPENMP=1 -j4 &> /dev/null
  - make install PREFIX=${HOME}/openblas 
  - export LD_LIBRARY_PATH=${HOME}/openblas/lib:$LD_LIBRARY_PATH
  - export LIBRARY_PATH=${HOME}/openblas/lib:$LIBRARY_PATH
  - export C_INCLUDE_PATH=${HOME}/openblas/include:$C_INCLUDE_PATH
  - export CPLUS_INCLUDE_PATH=${HOME}/openblas/include:$CPLUS_INCLUDE_PATH
  - cd ../glog
  - ./configure --enable-shared --prefix=${HOME}/glog
  - touch configure.ac aclocal.m4 configure Makefile.am Makefile.in
  - make -j4 &> /dev/null
  - make install
  - export LD_LIBRARY_PATH=${HOME}/glog/lib:$LD_LIBRARY_PATH
  - export LIBRARY_PATH=${HOME}/glog/lib:$LIBRARY_PATH
  - export CPLUS_INCLUDE_PATH=${HOME}/glog/include:$CPLUS_INCLUDE_PATH
  - cd ../..
  - make
  - export BLITZ_PREFIX=`pwd`
  - export LD_LIBRARY_PATH=${BLITZ_PREFIX}/lib:$LD_LIBRARY_PATH
  - export LIBRARY_PATH=${BLITZ_PREFIX}/lib:$LIBRARY_PATH
  - export CPLUS_INCLUDE_PATH=${BLITZ_PREFIX}/include:$CPLUS_INCLUDE_PATH
  - cd samples/cpu/convolution
  - make
  - cd -
  - export OMP_NUM_THREADS=4
  - export OMP_DYNAMIC="FALSE" 
script:
  - bash ./scripts/tests/cpu_convolution.sh
  - bash ./scripts/tests/cpu_pack.sh
