language: c++
compiler:
  - g++
os:
  - linux
addons:
  apt:
    packages:
    - libboost-system-dev
    - libboost-date-time-dev
    - libboost-chrono-dev
    - libboost-thread-dev
    - libgoogle-glog-dev
before_script:
  - export OMP_NUM_THREADS=16
  - make -j4
script:
  - ./scripts/tests/cpu.sh
