# backend: gpu
data_path: data/IMAGENET12
data_type: float
backend_type: CPU
# train or inference
model_type: train 
eval: false
epoches: 10
# for image is channel, width, height per image
data_shape: [3, 224, 224]
label_size: 1000
batch_size: 64
pool_size: 1

fillers:
-
    type: Gaussian
    name: f1
    loc: 0.0
    scale: 0.01

layers:
-
    type: Conv
    name: Conv1
    fshape: [64, 3, 3, 3]
    filler: f1
    stride: 1
    padding: 1
    activation: 
        type: Rectlin
    optimizer: op1
-
    type: Pooling
    name: Pooling1
    fshape: 2
    stride: 2
    op: max
-
    type: Conv
    name: Conv2
    fshape: [128, 64, 3, 3]
    filler: f1
    stride: 1
    padding: 1
    activation: 
        type: Rectlin
    optimizer: op1
-
    type: Pooling
    name: Pooling2
    fshape: 2
    stride: 2
    op: max
-
    type: Conv
    name: Conv3
    fshape: [256, 128, 3, 3]
    filler: f1
    stride: 1
    padding: 1
    activation: 
        type: Rectlin
    optimizer: op1
-
    type: Conv
    name: Conv4
    fshape: [256, 256, 3, 3]
    filler: f1
    stride: 1
    padding: 1
    activation: 
        type: Rectlin
    optimizer: op1
-
    type: Pooling
    name: Pooling3
    fshape: 2
    stride: 2
    op: max
-
    type: Conv
    name: Conv5
    fshape: [512, 256, 3, 3]
    filler: f1
    stride: 1
    padding: 1
    activation: 
        type: Rectlin
    optimizer: op1
-
    type: Conv
    name: Conv6
    fshape: [512, 512, 3, 3]
    filler: f1
    stride: 1
    padding: 1
    activation: 
        type: Rectlin
    optimizer: op1
-
    type: Pooling
    name: Pooling4
    fshape: 2
    stride: 2
    op: max
-
    type: Conv
    name: Conv7
    fshape: [512, 512, 3, 3]
    filler: f1
    stride: 1
    padding: 1
    activation: 
        type: Rectlin
    optimizer: op1
-
    type: Conv
    name: Conv8
    fshape: [512, 512, 3, 3]
    filler: f1
    stride: 1
    padding: 1
    activation: 
        type: Rectlin
    optimizer: op1
-
    type: Pooling
    name: Pooling5
    fshape: 2
    stride: 2
    op: max
-
    type: Affine
    name: Affine1
    nout: 4096
    filler: f1
    activation:
        type: Rectlin
    optimizer: op1
-
    type: Affine
    name: Affine2
    nout: 4096
    filler: f1
    activation:
        type: Rectlin
    optimizer: op1
-
    type: Affine
    name: Affine3
    nout: 1000
    filler: f1
    activation: 
        type: Softmax
        short_cut: true
    optimizer: op1
-
    cost: 
        type: CrossEntropyMulti

scheduler:
-
    type: GradientDescent
    name: op1
    learning_rate: 0.01
    step: 10
    change: 0.1
    momentum_coef: 0.9
    decay: 0.0005

callbacks:
-
    type: Progressbar
    step: 1
